---
abstract: 'Reboot is a perl low level library which permits to rebootyour computer in several ways [UNIX ONLY]'
author:
  - 'Edoardo Mantovani, aka BASEBAND <Baseband@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::SearchPath: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.143240'
license: BSD2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Reboot
no_index:
  directory:
    - t
requires:
  strict: '0'
version: '1.00'
