#!/usr/bin/perl

package Reboot;

use strict;
use warnings;

our $VERSION = '1.00';
use base qw(Exporter DynaLoader);

# export BOOT constants

use constant{
  LINUX_REBOOT_MAGIC1 => 0xfee1dead,
  LINUX_REBOOT_MAGIC2 => 672274793,
  LINUX_REBOOT_MAGIC2A => 85072278,
  LINUX_REBOOT_MAGIC2B => 369367448,
  LINUX_REBOOT_MAGIC2C => 537993216,
  LINUX_REBOOT_CMD_RESTART => 0x01234567,
  LINUX_REBOOT_CMD_HALT => 0xCDEF0123,
  LINUX_REBOOT_CMD_CAD_ON => 0x89ABCDEF,
  LINUX_REBOOT_CMD_CAD_OFF => 0x00000000,
  LINUX_REBOOT_CMD_POWER_OFF => 0x4321FEDC,
  LINUX_REBOOT_CMD_RESTART2 => 0xA1B2C3D4,
  LINUX_REBOOT_CMD_SW_SUSPEND => 0xD000FCE2,
  LINUX_REBOOT_CMD_KEXEC => 0x45584543,
};

our %EXPORT_TAGS = (
  boot_const => [qw(
  LINUX_REBOOT_MAGIC1
  LINUX_REBOOT_MAGIC2
  LINUX_REBOOT_MAGIC2A
  LINUX_REBOOT_MAGIC2B
  LINUX_REBOOT_MAGIC2C
  LINUX_REBOOT_CMD_RESTART
  LINUX_REBOOT_CMD_HALT
  LINUX_REBOOT_CMD_CAD_ON
  LINUX_REBOOT_CMD_CAD_OFF
  LINUX_REBOOT_CMD_POWER_OFF
  LINUX_REBOOT_CMD_RESTART2
  LINUX_REBOOT_CMD_SW_SUSPEND
  LINUX_REBOOT_CMD_KEXEC

  )],
  boot_funct => [qw(
  
  
  
  )],
  
);

our @EXPORT = (
   @{ $EXPORT_TAGS{ boot_const } },
   @{ $EXPORT_TAGS{ boot_funct } },
   );
   
1;
